=== cyberwizard1001/ncp_lab_eval/Q2/lor.dtd
<!DOCTYPE note
[
<!ELEMENT LOR (Consent,Prefix,FirstName,LastName,Organization,Title,RelationshipToStudent,Telephone,Email,AcademicPerformance,IntellectualAbility,AbilityToExpress,MotivationForProposedField,Admit)>
<!ELEMENT Consent (#PCDATA)>
<!ELEMENT Prefix (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Organization (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT RelationshipToStudent (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT AcademicPerformance (#PCDATA)>
<!ELEMENT IntellectualAbility (#PCDATA)>
<!ELEMENT AbilityToExpress (#PCDATA)>
<!ELEMENT MotivationForProposedField (#PCDATA)>
<!ELEMENT Admit (#PCDATA)>
<!ELEMENT Signature (#PCDATA)>
]>

=== cyberwizard1001/ncp_lab_eval/Q2/lor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LOR SYSTEM "lor.dtd">
<LOR>
    <Consent>Yes</Consent>
    <Prefix>Dr</Prefix>
    <FirstName>Senthilkumar</FirstName>
    <LastName>T</LastName>
    <Organization>Amrita Vishwa Vidyapeetham</Organization>
    <Title>Associate Professor</Title>
    <RelationshipToStudent>Associate Professor</RelationshipToStudent>
    <Telephone>1234567890</Telephone>
    <Email>thisisanemail@gmail.com</Email>
    <AcademicPerformance>Upper 1 to 2%</AcademicPerformance>
    <IntellectualAbility>Upper 10%</IntellectualAbility>
    <AbilityToExpress>Upper 1 to 2%</AbilityToExpress>
    <MotivationForProposedField>Upper 1 to 2%</MotivationForProposedField>
    <Admit>Yes</Admit>
    <Signature>Senthilkumar T</Signature>
</LOR>
